version: '3.4'
services:

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # Nginx Service
  nginx:
    build:
      context: .docker/nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www

  # MySQL Service
  mysql:
    image: mariadb
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_DATABASE
    volumes:
      - ./:/var/www

  # Workspace Service
  workspace:
    build:
      context: .
      target: workspace
    container_name: workspace
    depends_on:
      - php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
